from django.db import models
from django.contrib.auth.models import User

class Relationsips(models.Model):
    date = models.DateField(primary_key=True)
    self = models.IntegerField(default=0)
    father = models.IntegerField(default=0)
    mother = models.IntegerField(default=0)
    siblings = models.IntegerField(default=0)
    friends = models.IntegerField(default=0)
    grand_parents = models.IntegerField(default=0)
    uncles = models.IntegerField(default=0)
    aunts = models.IntegerField(default=0)
    neighbors = models.IntegerField(default=0)
    colleagues = models.IntegerField(default=0)
    bosses = models.IntegerField(default=0)
    teachers = models.IntegerField(default=0)
    clients = models.IntegerField(default=0)
    money = models.IntegerField(default=0)
    bosses = models.IntegerField(default=0)
    teachers = models.IntegerField(default=0)
    clients = models.IntegerField(default=0)
    money = models.IntegerField(default=0)
    work = models.IntegerField(default=0)
    time = models.IntegerField(default=0)
    community = models.IntegerField(default=0)

class Skills(models.Model):
    date = models.DateField()
    gratitude = models.IntegerField(default=0)
    communication = models.IntegerField(default=0)
    problem_solving = models.IntegerField(default=0)
    leadership = models.IntegerField(default=0)
    teamwork = models.IntegerField(default=0)
    emotional_intelligence = models.IntegerField(default=0)
    adaptability = models.IntegerField(default=0)
    work_ethic = models.IntegerField(default=0)
    attention_to_details = models.IntegerField(default=0)

class Changes_Internally(models.Model):
    date = models.DateField()
    self_awareness = models.IntegerField(default=0)
    self_belief = models.IntegerField(default=0)
    self_confidence = models.IntegerField(default=0)
    self_discipline = models.IntegerField(default=0)
    self_expressions = models.IntegerField(default=0)
    self_feelings = models.IntegerField(default=0)
    self_gratitude = models.IntegerField(default=0)
    self_happiness = models.IntegerField(default=0)
    self_impression = models.IntegerField(default=0)
    self_joy = models.IntegerField(default=0)
    self_knowledge = models.IntegerField(default=0)
    self_learning = models.IntegerField(default=0)
    self_management = models.IntegerField(default=0)
    self_negotiation = models.IntegerField(default=0)
    self_observation = models.IntegerField(default=0)
    self_possession = models.IntegerField(default=0)
    self_quickness = models.IntegerField(default=0)
    self_reliability = models.IntegerField(default=0)
    self_success = models.IntegerField(default=0)
    self_treatment = models.IntegerField(default=0)
    self_unity = models.IntegerField(default=0)
    self_victory = models.IntegerField(default=0)
    self_worth = models.IntegerField(default=0)
    self_youngness = models.IntegerField(default=0)
    self_zeal = models.IntegerField(default=0)

class feedback(models.Model):
    name = models.CharField(max_length=100)
    review = models.CharField(max_length=100)
    bootcamp_date = models.DateField()
    bootcamp_day = models.IntegerField()